-- ALTER TABLE examples
ALTER TABLE Accounts ADD COLUMN DESCRIPTION VARCHAR(1000);

ALTER TABLE Transactions ADD COLUMN MODIFIED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE Journal_Entries ADD CONSTRAINT fk_journal_txn 
    FOREIGN KEY (TRANSACTION_ID) REFERENCES Transactions(ID) ON DELETE CASCADE;
